### ISSUE TITLE
Website has changed kindly update repo

### ISSUE THREAD

**Issue by 18bce133** [0102L/ASU-Class-Notifier#1]
ASU website has changed this script does not work further.

**Comment by 0102L** [comment]
Hi thanks for bringing this to my attention. I don't really maintain this repo anymore since I graduated from ASU but the URL does change for each new semester. If it's just the URL change, I can push an update to the Spring 2023 catalogue later today.

**Comment by 18bce133** [comment]
Actually issue is not related to link it is that they have changed their portal and shifted to javascript DOM-based.

**Comment by 0102L** [comment]
Ah so what happened was this script was using a legacy version of the catalogue that was easier to scrape and it looks like that might've been discontinued. I'll see how hard it is to convert this to the current search/find a new url for the legacy catalogue if that still exists.

**Comment by 18bce133** [comment]
Never mind, I have written a new code using selenium. Thank you

**Comment by 0102L** [comment]
No problem - sorry I've been too busy to look at it. Thanks for letting me know the website changed. I'll probably archive the repo if I decide not to update.
